Minimal spi master rebase
tillitis/tillitis-key1 pull request #207
Opened 2024-04-18 13:23 UTC by dehanj

Rebased on main, and squashed to two commits.
- SPI master construction
- Testbench and simulation

2024-04-18 13:25 UTC, dehanj commented
To minimize the risk during rebase and squash I created a new branch and a new PR.
I suggest we merge this isntead of https://github.com/tillitis/tillitis-key1/pull/203 when we are ready and have tested it properly.

2024-04-18 13:33 UTC, dehanj commented
I have verified both the builds with and without the SPI master. So far it looks good.

2024-04-19 07:47 UTC, dehanj commented
Added SPI build to CI. Also divided the builds to different jobs, to make it easier to see what fails or not.

2024-04-19 10:37 UTC, dehanj commented
This PR should be merged after #208, since it is a risk here that cache fetches the wrong bitstream.

2024-04-22 06:51 UTC, secworks commented on hw/application_fpga/Makefile
> +#
Är detta för ny target. Annar bode den texten flyttas till beskrivning av ny target och formuleras om.

2024-04-22 11:38 UTC, secworks requested changes

2024-04-22 11:38 UTC, secworks commented on hw/application_fpga/Makefile
> +# otherwise there is a risk of including the it unknowingly.
'the it'. Remove 'it'.

2024-04-22 11:38 UTC, secworks commented on hw/application_fpga/Makefile
> +# otherwise there is a risk of including the it unknowingly.
Or change 'it' to 'SPI master'.

2024-04-25 08:49 UTC, dehanj commented on hw/application_fpga/Makefile
> +# otherwise there is a risk of including the it unknowingly.
Fixed.

2024-04-25 09:45 UTC, dehanj commented on hw/application_fpga/core/tk1/tb/tb_tk1.v
> +  localparam ADDR_SPI_EN        = 8'h80;
I don't have the answer if we should use ifdef in the tb as well. One argument is that it is easier to have on build and make sure it all works. But on the other hand, if it is substantial difference and it is a risk that the test fails, yeah then it is better to have two.

But I think you will have to answer for what is the best approach here Joachim.

2024-04-25 09:46 UTC, dehanj commented on hw/application_fpga/core/tk1/tb/tb_tk1.v
> +  wire          tb_spi_ss;
See my response in the other comment.

2024-04-25 10:42 UTC, secworks commented on hw/application_fpga/core/tk1/tb/tb_tk1.v
> +  wire          tb_spi_ss;
Ok.

2024-04-25 10:49 UTC, secworks commented on hw/application_fpga/core/tk1/tb/tb_tk1.v
> +  localparam ADDR_SPI_EN        = 8'h80;
Having excess symbolic names should pose not problem. A linter may give warnings (This is not Go after all).
But ports in the DUT and associated wires should cause at least warnings during build of the som environment, and cause confusion. Testbench functionality such a state monitor, state display may also become problematic.

And most importantly. The test cases in a testbench should test the functionality of the DUT. This means that the DUT and the TB are in sync in terms of functionality. A self-checking test case that tests a functionality that don't exist in the DUT should fail.

To summarize. If we have functionality in the DUT (the core) that is compile time optional, we should also have the test functionality for that functionality compile time optional.

2024-04-29 07:43 UTC, dehanj commented on hw/application_fpga/core/tk1/tb/tb_tk1.v
> +  localparam ADDR_SPI_EN        = 8'h80;
Sounds great. Can you add it?

2024-05-07 07:53 UTC, mchack-work commented
SPI control addresses were missing from tk1_mem.h. I added them.

2024-06-12 09:07 UTC, mchack-work approved these changes

2024-06-12 09:07 UTC, merged